"use client";

import { FormEvent, useState } from "react";
import { Icon } from "@/app/components/icons";
import { PageContainer } from "@/app/components/page-container";
import { requestHistory as initialRequestHistory } from "@/app/lib/mock-data";
import type { RequestRecord } from "@/app/lib/mock-data";
import { StatusBadge } from "@/app/components/status-badge";
import { formatDisplayDate } from "@/app/lib/formatters";

type RequestType = "Leave" | "Remote Work";
type LeaveType = "Annual Leave" | "Sick Leave" | "Casual Leave" | "Unpaid Leave";

const leaveTypes: LeaveType[] = ["Annual Leave", "Sick Leave", "Casual Leave", "Unpaid Leave"];

export default function RequestsPage() {
  const [requestType, setRequestType] = useState<RequestType>("Leave");
  const [leaveType, setLeaveType] = useState<LeaveType>("Annual Leave");
  const [fromDate, setFromDate] = useState("2026-08-21");
  const [toDate, setToDate] = useState("2026-08-21");
  const [reason, setReason] = useState("");
  const [note, setNote] = useState("");
  const [history, setHistory] = useState<RequestRecord[]>(initialRequestHistory);
  const [notice, setNotice] = useState("");

  function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const newRequest: RequestRecord = {
      id: `REQ-${history.length + 205}`,
      requestType: requestType === "Leave" ? leaveType : "Remote Work",
      dateRange: fromDate === toDate ? formatDisplayDate(fromDate) : `${formatDisplayDate(fromDate)} - ${formatDisplayDate(toDate)}`,
      duration: fromDate === toDate ? "1 day" : "Multiple days",
      submittedOn: "Today",
      status: "Pending",
      reason,
    };
    setHistory((current) => [newRequest, ...current]);
    setReason("");
    setNote("");
    setNotice("Your request was added to the history in this demo session.");
  }

  return <PageContainer>
    <section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-blue-600">Self-service</p><h2 className="mt-1.5 text-2xl font-semibold tracking-tight text-slate-950 sm:text-3xl">Requests</h2><p className="mt-2 text-sm leading-6 text-slate-500">Request leave or remote work and review your previous requests.</p></div><button type="button" onClick={() => document.getElementById("new-request-form")?.scrollIntoView({ behavior: "smooth", block: "start" })} className="inline-flex w-fit items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm shadow-blue-200 transition hover:bg-blue-700"><Icon name="plus" size={17} />New Request</button></section>

    <div className="grid items-start gap-6 xl:grid-cols-[1.25fr_0.75fr]">
      <section id="new-request-form" className="scroll-mt-24 rounded-2xl border border-slate-200 bg-white shadow-sm shadow-slate-200/40"><div className="border-b border-slate-100 p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-base font-semibold text-slate-950">Create a request</p><p className="mt-1 text-sm text-slate-500">Share the details and your manager will review it.</p></div><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><Icon name="file" size={18} /></span></div></div><form onSubmit={handleSubmit} className="space-y-6 p-5 sm:p-6"><fieldset><legend className="mb-3 text-sm font-semibold text-slate-800">Request type</legend><div className="grid grid-cols-2 gap-3"><button type="button" aria-pressed={requestType === "Leave"} onClick={() => setRequestType("Leave")} className={`flex items-center gap-3 rounded-xl border p-3.5 text-left transition ${requestType === "Leave" ? "border-blue-500 bg-blue-50 text-blue-700 ring-4 ring-blue-50" : "border-slate-200 text-slate-600 hover:border-slate-300 hover:bg-slate-50"}`}><span className={`flex h-8 w-8 items-center justify-center rounded-lg ${requestType === "Leave" ? "bg-white text-blue-600" : "bg-slate-100 text-slate-400"}`}><Icon name="calendar" size={16} /></span><span><span className="block text-sm font-semibold">Leave</span><span className="mt-0.5 block text-xs text-slate-500">Time away from work</span></span></button><button type="button" aria-pressed={requestType === "Remote Work"} onClick={() => setRequestType("Remote Work")} className={`flex items-center gap-3 rounded-xl border p-3.5 text-left transition ${requestType === "Remote Work" ? "border-blue-500 bg-blue-50 text-blue-700 ring-4 ring-blue-50" : "border-slate-200 text-slate-600 hover:border-slate-300 hover:bg-slate-50"}`}><span className={`flex h-8 w-8 items-center justify-center rounded-lg ${requestType === "Remote Work" ? "bg-white text-blue-600" : "bg-slate-100 text-slate-400"}`}><Icon name="briefcase" size={16} /></span><span><span className="block text-sm font-semibold">Remote Work</span><span className="mt-0.5 block text-xs text-slate-500">Work from another location</span></span></button></div></fieldset>
        {requestType === "Leave" ? <fieldset><legend className="mb-3 text-sm font-semibold text-slate-800">Leave type</legend><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{leaveTypes.map((type) => <button key={type} type="button" aria-pressed={leaveType === type} onClick={() => setLeaveType(type)} className={`rounded-xl border px-3 py-2.5 text-xs font-semibold transition ${leaveType === type ? "border-blue-500 bg-blue-50 text-blue-700" : "border-slate-200 text-slate-600 hover:bg-slate-50"}`}>{type}</button>)}</div></fieldset> : <div className="flex items-start gap-3 rounded-xl border border-blue-100 bg-blue-50/70 p-4 text-sm text-slate-600"><Icon name="briefcase" size={17} className="mt-0.5 shrink-0 text-blue-600" /><p>Remote work requests are reviewed against your team&apos;s availability and workplace policy.</p></div>}
        <div className="grid gap-4 sm:grid-cols-2"><div><label htmlFor="from-date" className="mb-2 block text-sm font-semibold text-slate-700">From date</label><input id="from-date" name="fromDate" type="date" required value={fromDate} onChange={(event) => setFromDate(event.target.value)} className="h-12 w-full rounded-xl border border-slate-200 bg-white px-3.5 text-sm text-slate-700 outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-100" /></div><div><label htmlFor="to-date" className="mb-2 block text-sm font-semibold text-slate-700">To date</label><input id="to-date" name="toDate" type="date" required min={fromDate} value={toDate} onChange={(event) => setToDate(event.target.value)} className="h-12 w-full rounded-xl border border-slate-200 bg-white px-3.5 text-sm text-slate-700 outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-100" /></div></div>
        <div><label htmlFor="request-reason" className="mb-2 block text-sm font-semibold text-slate-700">Reason</label><textarea id="request-reason" name="reason" required value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Briefly explain the reason for your request..." className="min-h-28 w-full resize-y rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm leading-6 text-slate-700 outline-none placeholder:text-slate-400 focus:border-blue-500 focus:ring-4 focus:ring-blue-100" /></div>
        <div><label htmlFor="request-note" className="mb-2 block text-sm font-semibold text-slate-700">Optional note <span className="font-normal text-slate-400">(optional)</span></label><textarea id="request-note" name="note" value={note} onChange={(event) => setNote(event.target.value)} placeholder="Add any supporting context..." className="min-h-20 w-full resize-y rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm leading-6 text-slate-700 outline-none placeholder:text-slate-400 focus:border-blue-500 focus:ring-4 focus:ring-blue-100" /></div>
        <div className="flex flex-col gap-3 border-t border-slate-100 pt-5 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs leading-5 text-slate-500">Your manager will be notified for review.</p><button type="submit" className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 text-sm font-semibold text-white shadow-sm shadow-blue-200 transition hover:bg-blue-700">Submit Request <Icon name="chevronRight" size={17} /></button></div>{notice ? <div role="status" className="flex items-center gap-3 rounded-xl border border-emerald-100 bg-emerald-50 px-4 py-3 text-sm text-emerald-800"><Icon name="check" size={17} className="shrink-0 text-emerald-600" />{notice}</div> : null}
      </form></section>

      <aside className="rounded-2xl border border-slate-200 bg-slate-950 p-6 text-white shadow-sm shadow-slate-200/40"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-600"><Icon name="sparkles" size={18} /></div><h3 className="mt-5 text-xl font-semibold tracking-tight">Make planning easier</h3><p className="mt-2 text-sm leading-6 text-slate-400">Give your team enough context to review requests quickly and keep schedules in sync.</p><div className="mt-7 space-y-4 border-t border-slate-800 pt-5"><div className="flex gap-3"><span className="mt-0.5 text-blue-400">01</span><div><p className="text-sm font-medium text-slate-200">Choose your request type</p><p className="mt-1 text-xs leading-5 text-slate-500">Leave requests include the applicable leave category.</p></div></div><div className="flex gap-3"><span className="mt-0.5 text-blue-400">02</span><div><p className="text-sm font-medium text-slate-200">Add clear dates and context</p><p className="mt-1 text-xs leading-5 text-slate-500">A short reason helps your manager respond faster.</p></div></div><div className="flex gap-3"><span className="mt-0.5 text-blue-400">03</span><div><p className="text-sm font-medium text-slate-200">Track approval here</p><p className="mt-1 text-xs leading-5 text-slate-500">Every submission appears in your request history.</p></div></div></div></aside>
    </div>

    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm shadow-slate-200/40"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-5 sm:p-6"><div><p className="text-base font-semibold text-slate-950">Request History</p><p className="mt-1 text-sm text-slate-500">Review your recent leave and remote work submissions.</p></div><span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-medium text-slate-600">{history.length} requests</span></div><div className="hidden max-h-80 overflow-x-auto overflow-y-auto md:block"><table className="w-full min-w-[920px] text-left"><thead className="sticky top-0 z-10 bg-white"><tr className="border-b border-slate-100 text-[11px] font-bold uppercase tracking-[0.14em] text-slate-400"><th className="px-5 py-3.5 sm:px-6">Request type</th><th className="px-5 py-3.5">Date range</th><th className="px-5 py-3.5">Duration</th><th className="px-5 py-3.5">Submitted on</th><th className="px-5 py-3.5">Status</th><th className="px-5 py-3.5">Reason</th></tr></thead><tbody className="divide-y divide-slate-100">{history.map((request) => <tr key={request.id} className="text-sm transition-colors hover:bg-slate-50"><td className="px-5 py-4 font-medium text-slate-800 sm:px-6">{request.requestType}</td><td className="px-5 py-4 text-slate-600">{request.dateRange}</td><td className="px-5 py-4 text-slate-500">{request.duration}</td><td className="px-5 py-4 text-slate-500">{request.submittedOn}</td><td className="px-5 py-4"><StatusBadge status={request.status} showDot /></td><td className="max-w-[240px] truncate px-5 py-4 text-slate-500">{request.reason}</td></tr>)}</tbody></table></div><div className="max-h-80 divide-y divide-slate-100 overflow-y-auto md:hidden">{history.map((request) => <article key={request.id} className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-slate-900">{request.requestType}</p><p className="mt-1 text-xs text-slate-500">{request.dateRange} · {request.duration}</p></div><StatusBadge status={request.status} showDot /></div><div className="mt-4 rounded-xl bg-slate-50 p-3.5"><div className="grid grid-cols-2 gap-3 text-xs"><div><p className="text-slate-400">Submitted on</p><p className="mt-1 font-medium text-slate-700">{request.submittedOn}</p></div><div><p className="text-slate-400">Request ID</p><p className="mt-1 font-medium text-slate-700">{request.id}</p></div></div><p className="mt-3 border-t border-slate-200 pt-3 text-xs leading-5 text-slate-600">{request.reason}</p></div></article>)}</div></section>
  </PageContainer>;
}
